# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5557e7397878341ece142051ca0ca1761d12a2a6f8960f6a25cdb7b87efb4d66a4af089db2ecae0891f6a1a8017a94327f90f7230f52462c215574bb54f4a1a

test:
  secret_key_base: 395ea11cc7cb684cb7dcef7e29eb7a28e48299ef50c5b3290611b1209e4bbd62ef3f4a72c60cffbdb83272ff8428e7fd1135c27340a70781556cf85c07065281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
